### ISSUE TITLE
Unity 5.5 compatibility ?

### ISSUE THREAD

**Issue by PxSonny** [hecomi/uRaymarching#1]
Hello, 

First great coding and asset. Code is very clean and easy to read. 

I am running your examples scenes from Windows and DX11. I did not try DX9. And the scene hex floor works good, while Mod world and Sphere box morphing don't. 

I tried to use a simple: `return Sphere(pos, 0.5);` too but the cube still gets drawn. 

So I guess there are some differences while running DirectX, do you plan to get it compatible at some point? Or you don't have a Windows computer and hope someone could participate? 

Thanks.

**Comment by PxSonny** [comment]
Seems it's not a DX11 issue, as I tried to run Unity in OpenGL on Windows. And it does the same result. So maybe Unity 5.5.0 issue?

**Comment by PxSonny** [comment]
Found that the latest commit works fine, with either DX11 or OpenGL on Windows and Unity 5.5. So Thanks :)

**Comment by hecomi** [comment]
Thanks for the comment! I guess your project was running under **Forward** Rendering. uRaymarching modifies the G-Buffer and it can be done only under **Deferred** Rendering. 

Since Unity 5.5, the location of the setting of the *Rendering Path* has changed from *Player Settings* to *Graphics Settings*.

![graphics](https://cloud.githubusercontent.com/assets/493433/21607052/f749f400-d1f6-11e6-85aa-6f61036fa63e.PNG)

And I wrote an article about uRaymarching. I hope it will help you use this plugin.
- Original (Japanese): http://tips.hecomi.com/entry/2016/10/11/225541
- English (using Google Translation): https://translate.google.com/translate?hl=ja&sl=auto&tl=en&u=http%3A%2F%2Ftips.hecomi.com%2Fentry%2F2016%2F10%2F11%2F225541

**Comment by PxSonny** [comment]
Hi,

Oh forward rendering it makes sense yes, you are right.

Thank you I will check your article. ^_^
