### ISSUE TITLE
glitched Follow Object Scale 

### ISSUE THREAD

**Issue by Seremonik** [hecomi/uRaymarching#18]
After checking Follow Object Scale this visual glitch appear:
![image](https://user-images.githubusercontent.com/9090982/52898777-4a464580-31e2-11e9-9e68-429d9ded356e.png)
 for the simple two cubes intersection

**Comment by hecomi** [comment]
I've fixed, so could you try the latest one?
[uRaymarching-v1.0.3rc.zip](https://github.com/hecomi/uRaymarching/files/2872737/uRaymarching-v1.0.3rc.zip)

\~x1000 seems to work well in my environment, however it still has a problem caused by a low precision when scaling up the object to x1000\~:
<img width="638" alt="problem" src="https://user-images.githubusercontent.com/493433/52909947-aa68e480-32d3-11e9-9338-89d3fb14f481.PNG">

I've attempted to fix it and found a solution by doing the raymarching loop in an object space (https://gist.github.com/hecomi/273545c81c880474a51c42b95def8040) but it caused the other problems..., so I'll do it in the future.

**Comment by Seremonik** [comment]
Yup it works 👍 
with your great asset and your help with bugs i managed to make my first fractal :)
![image](https://user-images.githubusercontent.com/9090982/52910677-4e826980-329b-11e9-86db-5058bc12b193.png)
Thank you for such a great Unity asset!

**Comment by hecomi** [comment]
Cool!! I'm very glad to hear that. Thank you for using this asset and helping me fix bugs.

**Comment by skaale** [comment]
Hi hecomi ,

Any chance for Updating  uRaymarching for 2019.2 HDRP ?

**Comment by hecomi** [comment]
Yes, I have a plan but at first I'll support LWRP and it will not be soon, sorry.

**Comment by skaale** [comment]
HI Hecomi,

Thanks:-) .. I will try to update you amazing job on Uraymarching to support LWRP/HDRP planing to do a VFX approach with a fractal world for VR and also to support collision  - hope it ok that I share some of my progress with you :-) 
Have a nice day 
Best Daniel 
https://www.youtube.com/watch?v=OGOuNpk_wEI

https://www.youtube.com/watch?v=mKgOfSBFD_4
